spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: da059d0b26807201a8c9
            clientSecret: d6c2ca786c1fa3a1f312e879909a8e86a6854bea
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user
    provider:
      github:
        authorization-uri: https://github.com/login/oauth/authorize
        token-uri: https://github.com/login/oauth/access_token
        user-info-uri: https://api.github.com/user